CREATE TABLE airbnb_product (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 상품 고유 ID
    product_title VARCHAR2(100) NOT NULL,                            -- 상품 제목
    product_description VARCHAR2(500),                               -- 상품 설명
    product_date DATE DEFAULT SYSDATE,                               -- 상품 등록 날짜 (기본값: 오늘)
    product_image VARCHAR2(255),                                     -- 상품 이미지 경로
    max_quantity NUMBER CHECK (max_quantity BETWEEN 1 AND 10),       -- 숙박 가능 수량 (1~10개 사이)
    host_id VARCHAR2(50) NOT NULL,                                   -- 상품 등록한 HOST ID
    is_powerball NUMBER(1) DEFAULT 0 CHECK (is_powerball IN (0, 1)),   -- 최고 관리자 추천 여부 (0: 기본, 1: 추천)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                  -- 생성 시점
    FOREIGN KEY (host_id) REFERENCES airbnb_admin(admin_id)          -- HOST ID는 관리자 테이블(airbnb_admin)과 연동
);

INSERT INTO airbnb_product (product_title, product_description, product_image, max_quantity, host_id)
VALUES ('서울 한옥 숙소', '전통 한옥에서 하룻밤을!', '/uploads/hanok.png', 3, 'host');

