-- AirBnb User테이블 만들기



CREATE TABLE airbnb_user (
    user_num NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- 사용자 고유 ID
    user_id VARCHAR2(50) UNIQUE NOT NULL,                              -- 사용자 이름 (로그인용)
    user_pwd VARCHAR2(255) NOT NULL,                                   -- 비밀번호 (해시 형태 저장)
    user_email VARCHAR2(100) UNIQUE NOT NULL,                          -- 이메일 주소
    user_phone VARCHAR2(15),                                           -- 연락처
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                     -- 가입 일자
    last_login TIMESTAMP,                                              -- 마지막 로그인 시간
    user_addr VARCHAR2(255),                                           -- 주소
    status VARCHAR2(20) DEFAULT 'ACTIVE',                              -- 상태 (ACTIVE, INACTIVE 등)
    profile_image VARCHAR2(255)                                        -- 프로필 이미지 경로
);

insert into airbnb_user (
	user_id, user_pwd, user_email, user_phone, user_addr, status, profile_image)
	 values ('nyahaha1', '1111', 'nyahaha1@gmail.com', '010-1111-1111', '서울시 마포구', 'ACTIVE', '/images/hyunsuk.jpg');






